### ISSUE TITLE
Multiple results

### ISSUE THREAD

**Issue by piglet-007** [mmphego/face_mask_detection_openvino#2]
Hello, great work. 

What changes I should do into the code to detect multiple results? Now, the system detects multiple faces but only one mask. For example, if there are 3 people, 2 with mask and 1 without mask, the system detect 3 faces but detects only one result for masks and show that all have mask.

Thanks.

**Comment by mmphego** [comment]
Hi,
The facemask detection model I used unfortunately, only detects one person wearing a mask in the frame. You could look for alternative models on these repos: https://github.com/search?q=facemask+detection
